version: '3'
services:
  app:
    build: .
    environment:
      DATABASE_URI: mongodb://mongodb:27017/myapp
    ports:
      - 3000:3000
    depends_on:
      - mongodb
  mongodb:
    image: mongo
    ports:
      - 27017:27017
